services:
  hybrid-crs-api:
    container_name: hybrid-crs-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    restart: unless-stopped
