include:
  - llm/docker-compose.yaml
  - frontend/docker-compose.yaml

services:
  api:
    container_name: hybrid-crs-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    tty: true
    stdin_open: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOCAL_SERVICES_HOST=localhost.gateway
      - OLLAMA_HOST=localhost.gateway
    extra_hosts:
      - "localhost.gateway:host-gateway"

    volumes:
      - ./data_processing/datasets:/api/data_processing/datasets
      - ./recsys/saved:/api/recsys/saved

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - nvidia.com/gpu=all
              capabilities:
                - gpu
