services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    # Expose Ollama API
    ports:
      - 11434:11434
    pull_policy: always
    tty: true
    restart: unless-stopped

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - nvidia.com/gpu=all
              capabilities:
                - gpu

  falkordb:
    image: falkordb/falkordb:latest
    container_name: falkordb
    environment:
      - FALKORDB_ARGS=MAX_QUEUED_QUERIES 50 TIMEOUT_MAX 300000 TIMEOUT_DEFAULT 300000
    ports:
      - 6379:6379
      - 3000:3000
    volumes:
      - ./falkordb_storage:/var/lib/falkordb/data
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  ollama: {}
