data_path: ../data_processing/datasets/processed

seed: 2025
use_gpu: false
device: cuda

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
normalize_all: True

# Training and evaluation config
epochs: 300
train_batch_size: 2048
eval_batch_size: 2048
stopping_step: 10

train_neg_sample_args: 
  distribution: uniform
  sample_num: 1

eval_args:
  split: {'RS': [0.8,0.1,0.1]}
  order: RO
  group_by: user
  # mode: uni100
  mode: full

metrics: [Recall, MRR, NDCG, MAP, Precision]
topk: 10
valid_metric: NDCG@10

## XGBoost
xgb_num_boost_round: 100
xgb_early_stopping_rounds: 10
xgb_verbose_eval: 10

## LightGBM
lgb_params: {'verbose': 1}
lgb_num_boost_round: 100
